//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Liber.Forms.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "18.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{}")]
        public string RecentPaths {
            get {
                return ((string)(this["RecentPaths"]));
            }
            set {
                this["RecentPaths"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Culture {
            get {
                return ((string)(this["Culture"]));
            }
            set {
                this["Culture"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[]")]
        public string CustomColors {
            get {
                return ((string)(this["CustomColors"]));
            }
            set {
                this["CustomColors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Inactive {
            get {
                return ((bool)(this["Inactive"]));
            }
            set {
                this["Inactive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[\r\n  {\r\n    \"filter\": \"^7\",\r\n    \"type\": \"incomeTaxExpense\",\r\n    \"strict\": true\r" +
            "\n  },\r\n  {\r\n    \"filter\": \"^6\",\r\n    \"type\": \"otherIncomeExpense\",\r\n    \"strict\"" +
            ": true\r\n  },\r\n  {\r\n    \"filter\": \"^1[5689]\",\r\n    \"type\": \"otherAsset\"\r\n  },\r\n  " +
            "{\r\n    \"filter\": \"^17\",\r\n    \"type\": \"fixedAsset\"\r\n  },\r\n  {\r\n    \"filter\": \"^2[" +
            "5-9]\",\r\n    \"type\": \"longTermLiability\"\r\n  },\r\n  {\r\n    \"filter\": \"Accumulated O" +
            "ther Comprehensive\",\r\n    \"cashFlow\": \"otherEquity\",\r\n    \"otherEquity\": true,\r\n" +
            "    \"strict\": true\r\n  },\r\n  {\r\n    \"filter\": \"(Capital|Unrealized) (Gain|Loss|Ap" +
            "preciation)\",\r\n    \"type\": \"otherIncomeExpense\",\r\n    \"cashFlow\": \"gainLoss\",\r\n " +
            "   \"strict\": true\r\n  },\r\n  {\r\n    \"filter\": \"Deferred.*Tax.*(Asset|Liability)\",\r" +
            "\n    \"cashFlow\": \"operating\",\r\n    \"strict\": true\r\n  },\r\n  {\r\n    \"filter\": \"US " +
            "Treasury Bill\",\r\n    \"cashFlow\": \"investing\",\r\n    \"strict\": true\r\n  },\r\n  {\r\n  " +
            "  \"filter\": \"(Retained Earning|Accumulated Deficit)\",\r\n    \"type\": \"equity\",\r\n  " +
            "  \"equity\": true,\r\n    \"strict\": true\r\n  },\r\n  {\r\n    \"filter\": \"Charles Schwab " +
            "Individual Short[-\\\\s]Term\",\r\n    \"cashFlow\": \"investing\",\r\n    \"strict\": true\r\n" +
            "  },\r\n  {\r\n    \"filter\": \"Charles Schwab Individual Long[-\\\\s]Term\",\r\n    \"type\"" +
            ": \"otherAsset\",\r\n    \"cashFlow\": \"investing\",\r\n    \"strict\": true\r\n  },\r\n  {\r\n  " +
            "  \"filter\": \"Chase Bank\",\r\n    \"color\": -16752968\r\n  },\r\n  {\r\n    \"filter\": \"Ven" +
            "mo\",\r\n    \"color\": -16741121\r\n  },\r\n  {\r\n    \"filter\": \"US Bank\",\r\n    \"color\": " +
            "-3200458\r\n  },\r\n  {\r\n    \"filter\": \"Fidelity Investments\",\r\n    \"color\": -133999" +
            "99\r\n  },\r\n  {\r\n    \"filter\": \"Charles Schwab\",\r\n    \"color\": -16736805\r\n  },\r\n  " +
            "{\r\n    \"filter\": \"Wealthfront\",\r\n    \"color\": -12042053\r\n  },\r\n  {\r\n    \"filter\"" +
            ": \"Goldman Sachs\",\r\n    \"color\": -9201210\r\n  },\r\n  {\r\n    \"filter\": \"PNC Financi" +
            "al Services\",\r\n    \"color\": -688091\r\n  },\r\n  {\r\n    \"filter\": \"Citibank\",\r\n    \"" +
            "color\": -14328861\r\n  }\r\n]")]
        public string ImportRules {
            get {
                return ((string)(this["ImportRules"]));
            }
            set {
                this["ImportRules"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LastAccountGroup {
            get {
                return ((int)(this["LastAccountGroup"]));
            }
            set {
                this["LastAccountGroup"] = value;
            }
        }
    }
}
